/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica7;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author macpro2
 */
public class Encuesta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Encuesta.class.getName());
    Connection conn;
    
    String url = "jdbc:mysql://localhost:3306/encuesta";
    String user = "encuesta_user";
    String password = "encuesta_pass";
    
    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
        this.lbHoras.setText(Integer.toString(this.slHoras.getValue()));
        this.doConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbWin = new javax.swing.JRadioButton();
        rbLnx = new javax.swing.JRadioButton();
        rbMac = new javax.swing.JRadioButton();
        ckPrg = new javax.swing.JCheckBox();
        ckGrf = new javax.swing.JCheckBox();
        ckAdm = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        slHoras = new javax.swing.JSlider();
        btnGuardar = new javax.swing.JButton();
        lbHoras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elige un sistema operativo");

        jLabel2.setText("Elige tu especialidad");

        jLabel3.setText("Horas que le dedicas al trabajo");

        buttonGroup1.add(rbWin);
        rbWin.setSelected(true);
        rbWin.setText("Windows");

        buttonGroup1.add(rbLnx);
        rbLnx.setText("Linux");

        buttonGroup1.add(rbMac);
        rbMac.setText("Mac");

        ckPrg.setText("Programación");

        ckGrf.setText("Diseño Gráfico");

        ckAdm.setText("Administración");

        slHoras.setMaximum(24);
        slHoras.setValue(8);
        slHoras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slHorasStateChanged(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbHoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHoras.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbWin)
                                            .addComponent(rbLnx)
                                            .addComponent(rbMac)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckGrf)
                                    .addComponent(ckPrg)
                                    .addComponent(ckAdm)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnGuardar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(slHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(rbWin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLnx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckPrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckGrf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slHorasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slHorasStateChanged
          this.lbHoras.setText(Integer.toString(this.slHoras.getValue()));
    }//GEN-LAST:event_slHorasStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String sRes = "";
        String sSO = "";
        String sPrg = "N";
        String sGrf = "N";
        String sAdm = "N";
        int iHrs = 0;
        
        sSO = "Windows";
        if (this.rbLnx.isSelected()) sSO = "Linux";
        if (this.rbMac.isSelected()) sSO = "Mac";

        if (this.ckPrg.isSelected()) sPrg = "S";
        if (this.ckGrf.isSelected()) sGrf = "S";
        if (this.ckAdm.isSelected()) sAdm = "S";
        
        iHrs = this.slHoras.getValue();
        
        sRes = String.format("%s,%s,%s,%s,%d\n",sSO,sPrg,sGrf,sAdm,iHrs);
        
        try { 
            // Create a FileWriter to write to a file named "example.txt"
            FileWriter w = new FileWriter("respuestas.txt",true);
            // Write a simple message to the file
            w.write(sRes);
            // Close the writer
            w.close();

            JOptionPane.showMessageDialog(this, "Mensaje guardado","Encuesta",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(this,"Error: "+e.getMessage(),"Encuesta",JOptionPane.ERROR_MESSAGE);
        }
        
        this.guardarDB(sSO,sPrg,sGrf,sAdm,iHrs);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Encuesta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckAdm;
    private javax.swing.JCheckBox ckGrf;
    private javax.swing.JCheckBox ckPrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbHoras;
    private javax.swing.JRadioButton rbLnx;
    private javax.swing.JRadioButton rbMac;
    private javax.swing.JRadioButton rbWin;
    private javax.swing.JSlider slHoras;
    // End of variables declaration//GEN-END:variables

    private void doConnect() {
        try {
            this.conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connection to MySQL established successfully!");
            // Perform database operations here
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Error en conexión con la BD: "+e.getMessage(),"Encuesta",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error connecting to MySQL: " + e.getMessage());
        }
    }

    private void guardarDB(String sSO, String sPrg, String sGrf, String sAdm, int iHrs) {
        Statement stmt;
        String sentIns = String.format("INSERT INTO respuestas (sSisOper,cProgra,cDiseno,cAdmon,iHoras) VALUES ('%s','%s','%s','%s',%d)",sSO,sPrg,sGrf,sAdm,iHrs);
        try {
            stmt = this.conn.createStatement();
            stmt.execute(sentIns);
        } catch (SQLException ex) {
            System.getLogger(Encuesta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(this,"No hay conexión con la BD","Encuesta",JOptionPane.ERROR_MESSAGE);
        }        
    }
}
