/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica5;

import javax.swing.ComboBoxModel;

/**
 *
 * @author macpro2
 */
public class Espejo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Espejo.class.getName());

    ComboBoxModel<String> cbm;
    
    /**
     * Creates new form Imitador
     */
    public Espejo() {
        initComponents();
        cbm = this.cbLista.getModel();
        this.cbLista1.setModel(cbm);
        this.spSpinner1.setModel(this.spSpinner.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbOpcion1 = new javax.swing.JRadioButton();
        rbOpcion2 = new javax.swing.JRadioButton();
        rbOpcion3 = new javax.swing.JRadioButton();
        ckOpcion4 = new javax.swing.JCheckBox();
        ckOpcion5 = new javax.swing.JCheckBox();
        ckOpcion6 = new javax.swing.JCheckBox();
        tfTextoX = new javax.swing.JTextField();
        cbLista = new javax.swing.JComboBox<>();
        spSpinner = new javax.swing.JSpinner();
        rbOpcion1_ = new javax.swing.JRadioButton();
        rbOpcion2_ = new javax.swing.JRadioButton();
        rbOpcion3_ = new javax.swing.JRadioButton();
        ckOpcion4_ = new javax.swing.JCheckBox();
        ckOpcion5_ = new javax.swing.JCheckBox();
        ckOpcion6_ = new javax.swing.JCheckBox();
        tfTextoX1 = new javax.swing.JTextField();
        cbLista1 = new javax.swing.JComboBox<>();
        spSpinner1 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Original");

        jLabel2.setText("Espejo");

        buttonGroup1.add(rbOpcion1);
        rbOpcion1.setSelected(true);
        rbOpcion1.setText("Opción 1");
        rbOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbOpcion2);
        rbOpcion2.setText("Opción 2");
        rbOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbOpcion3);
        rbOpcion3.setText("Opción 3");
        rbOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcion3ActionPerformed(evt);
            }
        });

        ckOpcion4.setText("Opción 4");
        ckOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckOpcion4ActionPerformed(evt);
            }
        });

        ckOpcion5.setText("Opción 5");
        ckOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckOpcion5ActionPerformed(evt);
            }
        });

        ckOpcion6.setText("Opción 6");
        ckOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckOpcion6ActionPerformed(evt);
            }
        });

        tfTextoX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTextoXKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTextoXKeyTyped(evt);
            }
        });

        buttonGroup2.add(rbOpcion1_);
        rbOpcion1_.setSelected(true);
        rbOpcion1_.setText("Opción 1");
        rbOpcion1_.setEnabled(false);

        buttonGroup2.add(rbOpcion2_);
        rbOpcion2_.setText("Opción 2");
        rbOpcion2_.setEnabled(false);

        buttonGroup2.add(rbOpcion3_);
        rbOpcion3_.setText("Opción 3");
        rbOpcion3_.setEnabled(false);

        ckOpcion4_.setText("Opción 4");
        ckOpcion4_.setEnabled(false);

        ckOpcion5_.setText("Opción 5");
        ckOpcion5_.setEnabled(false);

        ckOpcion6_.setText("Opción 6");
        ckOpcion6_.setEnabled(false);

        tfTextoX1.setEnabled(false);

        cbLista1.setEnabled(false);

        spSpinner1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbOpcion3_)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckOpcion6_))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rbOpcion2_)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckOpcion5_))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rbOpcion1_)
                                        .addGap(26, 26, 26)
                                        .addComponent(ckOpcion4_)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfTextoX1)
                                    .addComponent(cbLista1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbOpcion3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckOpcion6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rbOpcion2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckOpcion5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rbOpcion1)
                                        .addGap(26, 26, 26)
                                        .addComponent(ckOpcion4)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfTextoX)
                                    .addComponent(cbLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion1)
                    .addComponent(ckOpcion4)
                    .addComponent(tfTextoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion2)
                    .addComponent(ckOpcion5)
                    .addComponent(cbLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion3)
                    .addComponent(ckOpcion6)
                    .addComponent(spSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion1_)
                    .addComponent(ckOpcion4_)
                    .addComponent(tfTextoX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion2_)
                    .addComponent(ckOpcion5_)
                    .addComponent(cbLista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOpcion3_)
                    .addComponent(ckOpcion6_)
                    .addComponent(spSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion1ActionPerformed
        // TODO add your handling code here:
        this.rbOpcion1_.setSelected(this.rbOpcion1.isSelected());
    }//GEN-LAST:event_rbOpcion1ActionPerformed

    private void rbOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion2ActionPerformed
        this.rbOpcion2_.setSelected(this.rbOpcion2.isSelected());
    }//GEN-LAST:event_rbOpcion2ActionPerformed

    private void rbOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcion3ActionPerformed
        this.rbOpcion3_.setSelected(this.rbOpcion3.isSelected());
    }//GEN-LAST:event_rbOpcion3ActionPerformed

    private void ckOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckOpcion4ActionPerformed
        this.ckOpcion4_.setSelected(this.ckOpcion4.isSelected());
    }//GEN-LAST:event_ckOpcion4ActionPerformed

    private void ckOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckOpcion5ActionPerformed
        this.ckOpcion5_.setSelected(this.ckOpcion5.isSelected());
    }//GEN-LAST:event_ckOpcion5ActionPerformed

    private void ckOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckOpcion6ActionPerformed
        this.ckOpcion6_.setSelected(this.ckOpcion6.isSelected());
    }//GEN-LAST:event_ckOpcion6ActionPerformed

    private void tfTextoXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTextoXKeyTyped
        System.out.println("KeyTyped -> getKeyChar() "+evt.getKeyChar());
        System.out.println("KeyTyped -> getKeyCode() "+evt.getKeyCode());
        System.out.println("---------------------------");
    }//GEN-LAST:event_tfTextoXKeyTyped

    private void tfTextoXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTextoXKeyReleased
        System.out.println("KeyReleased -> getKeyChar() "+evt.getKeyChar());
        System.out.println("KeyReleased -> getKeyCode() "+evt.getKeyCode());
        System.out.println("---------------------------");
        this.tfTextoX1.setText(this.tfTextoX.getText());
        if(evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER){
            this.cbLista.addItem(this.tfTextoX.getText());
        }             
    }//GEN-LAST:event_tfTextoXKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Espejo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbLista;
    private javax.swing.JComboBox<String> cbLista1;
    private javax.swing.JCheckBox ckOpcion4;
    private javax.swing.JCheckBox ckOpcion4_;
    private javax.swing.JCheckBox ckOpcion5;
    private javax.swing.JCheckBox ckOpcion5_;
    private javax.swing.JCheckBox ckOpcion6;
    private javax.swing.JCheckBox ckOpcion6_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbOpcion1;
    private javax.swing.JRadioButton rbOpcion1_;
    private javax.swing.JRadioButton rbOpcion2;
    private javax.swing.JRadioButton rbOpcion2_;
    private javax.swing.JRadioButton rbOpcion3;
    private javax.swing.JRadioButton rbOpcion3_;
    private javax.swing.JSpinner spSpinner;
    private javax.swing.JSpinner spSpinner1;
    private javax.swing.JTextField tfTextoX;
    private javax.swing.JTextField tfTextoX1;
    // End of variables declaration//GEN-END:variables
}
