/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReproductorM;
import javafx.embed.swing.JFXPanel;
import javax.sound.sampled.Clip;
import java.io.File;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

// Pero requiere JavaFX en el proyecto
/**
 *
 * @author AlanSaurio
 */
public class ReproductorMP3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReproductorMP3.class.getName());
private final AudioPlayer hiloAudio;
private File archivoActual;
    /**
     * Creates new form ReproductorMP3
     */
    public ReproductorMP3() {
        initComponents();
        new JFXPanel();
        hiloAudio = new AudioPlayer();
        actualizarEstadoBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        PlayPause = new javax.swing.JButton();
        Seleccionar = new javax.swing.JButton();
        Detener = new javax.swing.JButton();
        Archivo = new javax.swing.JLabel();
        BarraProgreso = new javax.swing.JProgressBar();
        Estado = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayPause.setText(" ⏯️");
        PlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayPauseActionPerformed(evt);
            }
        });

        Seleccionar.setText("⏏️");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        Detener.setText("⏹️");
        Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerActionPerformed(evt);
            }
        });

        Archivo.setText("Archivo: ");

        Estado.setText("Estado: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Detener, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BarraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addComponent(Archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tiempo))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Archivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estado)
                .addGap(24, 24, 24)
                .addComponent(Tiempo)
                .addGap(18, 18, 18)
                .addComponent(BarraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seleccionar)
                    .addComponent(Detener)
                    .addComponent(PlayPause))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void actualizarEstadoBotones() {
    boolean reproduciendo = hiloAudio.estaReproduciendo();
    boolean pausado = hiloAudio.estaPausado();
    boolean archivoCargado = (archivoActual != null);

    PlayPause.setEnabled(archivoCargado);
    Detener.setEnabled(archivoCargado && (reproduciendo || pausado));
    
    // Actualizar texto del botón
    if (!reproduciendo && !pausado) {
        PlayPause.setText("▶️");
    } else if (pausado) {
        PlayPause.setText("▶️");
    } else {
        PlayPause.setText("⏸️");
    }
}

private String formatearTiempo(long segundos) {
    long min = segundos / 60;
    long seg = segundos % 60;
    return String.format("%02d:%02d", min, seg);
}

    private void PlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayPauseActionPerformed
if (!hiloAudio.estaReproduciendo() && !hiloAudio.estaPausado()) {
        // Primera vez - Reproducir
        hiloAudio.reproducir();
        Estado.setText("Estado: Reproduciendo");
    } else if (hiloAudio.estaReproduciendo()) {
        // Si está reproduciendo - Pausar
        hiloAudio.pausar();
        Estado.setText("Estado: Pausado");
    } else if (hiloAudio.estaPausado()) {
        // Si está pausado - Reanudar
        hiloAudio.reanudar();
        Estado.setText("Estado: Reproduciendo");
    }
    actualizarEstadoBotones();
    }//GEN-LAST:event_PlayPauseActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
            int resultado = jFileChooser1.showOpenDialog(this);
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        archivoActual = jFileChooser1.getSelectedFile();
        Archivo.setText("Archivo: " + archivoActual.getName());
        hiloAudio.cargarArchivo(archivoActual);
        Estado.setText("Estado: Cargado");
        Tiempo.setText("00:00 / " + formatearTiempo(hiloAudio.getDuracionTotal()));
        BarraProgreso.setValue(0);
        actualizarEstadoBotones();
    }
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerActionPerformed
    hiloAudio.detener();
    Estado.setText("Estado: Detenido");
    Tiempo.setText("00:00 / " + formatearTiempo(hiloAudio.getDuracionTotal()));
    BarraProgreso.setValue(0);
    actualizarEstadoBotones();

    }//GEN-LAST:event_DetenerActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    // ESTA LÍNEA OBLIGA A JAVA A BUSCAR TU JAVAFX SIN IMPORTAR LAS CONFIGURACIONES DEL IDE
    System.setProperty("javafx.module.path", "C:\\Users\\marti\\OneDrive\\Escritorio\\Nueva carpeta (2)\\openjfx-26.0.1_windows-x64_bin-sdk\\javafx-sdk-26.0.1\\lib");

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ReproductorMP3().setVisible(true);
        }
    });
}
class AudioPlayer extends Thread {
    private Object player; // Puede ser Clip o MediaPlayer
    private boolean pausado = false;
    private long posicionPausa = 0;
    private String tipoArchivo;

    public void cargarArchivo(File archivo) {
        String nombre = archivo.getName().toLowerCase();
        
        try {
            // Determinar tipo de archivo
            if (nombre.endsWith(".wav") || nombre.endsWith(".aiff") || nombre.endsWith(".au")) {
                tipoArchivo = "AUDIO_NATIVO";
                cargarAudioNativo(archivo);
            } else if (nombre.endsWith(".mp3") || nombre.endsWith(".m4a") || nombre.endsWith(".aac")) {
                tipoArchivo = "JAVAFX_MEDIA";
                cargarJavaFXMedia(archivo);
            } else {
                javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
                    "Formato no soportado: " + archivo.getName(), 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            pausado = false;
            posicionPausa = 0;
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
                "Error al cargar: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarAudioNativo(File archivo) throws Exception {
        if (player instanceof javax.sound.sampled.Clip) {
            ((javax.sound.sampled.Clip) player).close();
        }
        
        javax.sound.sampled.AudioInputStream audioInputStream = 
            javax.sound.sampled.AudioSystem.getAudioInputStream(archivo);
        javax.sound.sampled.Clip clip = javax.sound.sampled.AudioSystem.getClip();
        clip.open(audioInputStream);
        player = clip;
    }

    private void cargarJavaFXMedia(File archivo) {
        try {
            String uri = archivo.toURI().toString();
            javafx.scene.media.Media media = new javafx.scene.media.Media(uri);
            javafx.scene.media.MediaPlayer mediaPlayer = new javafx.scene.media.MediaPlayer(media);
            player = mediaPlayer;
            
            // Listener para cuando termine
            mediaPlayer.setOnEndOfMedia(() -> {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    Estado.setText("Estado: Finalizado");
                    actualizarEstadoBotones();
                    BarraProgreso.setValue(100);
                });
            });
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
                "Error con JavaFX: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    public void reproducir() {
        if (player == null) return;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                clip.setMicrosecondPosition(0);
                clip.start();
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                mediaPlayer.stop();
                mediaPlayer.play();
            }
            
            pausado = false;
            posicionPausa = 0;
            
            if (!this.isAlive()) {
                this.start();
            }
        } catch (Exception e) {
        }
    }

    public void pausar() {
        if (player == null) return;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                posicionPausa = clip.getMicrosecondPosition();
                clip.stop();
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                mediaPlayer.pause();
            }
            
            pausado = true;
        } catch (Exception e) {
        }
    }

    public void reanudar() {
        if (player == null) return;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                clip.setMicrosecondPosition(posicionPausa);
                clip.start();
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                mediaPlayer.play();
            }
            
            pausado = false;
        } catch (Exception e) {
        }
    }

    public void detener() {
        if (player == null) return;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                clip.stop();
                clip.setMicrosecondPosition(0);
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                mediaPlayer.stop();
            }
            
            pausado = false;
            posicionPausa = 0;
        } catch (Exception e) {
        }
    }

    public boolean estaReproduciendo() {
        if (player == null) return false;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                return clip.isRunning();
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                return javafx.scene.media.MediaPlayer.Status.PLAYING.equals(mediaPlayer.getStatus());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
            "Error al ejecutar acción: " + e.getMessage(), 
            "Error de Reproducción", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public boolean estaPausado() {
        if (player == null) return false;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                return pausado;
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                return javafx.scene.media.MediaPlayer.Status.PAUSED.equals(mediaPlayer.getStatus());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
            "Error al ejecutar acción: " + e.getMessage(), 
            "Error de Reproducción", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public long getDuracionTotal() {
        if (player == null) return 0;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                return clip.getMicrosecondLength() / 1000000;
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                return (long) (mediaPlayer.getTotalDuration().toSeconds());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
            "Error al ejecutar acción: " + e.getMessage(), 
            "Error de Reproducción", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        return 0;
    }

    public long getPosicionActual() {
        if (player == null) return 0;
        
        try {
            if (tipoArchivo.equals("AUDIO_NATIVO")) {
                javax.sound.sampled.Clip clip = (javax.sound.sampled.Clip) player;
                return clip.getMicrosecondPosition() / 1000000;
            } else if (tipoArchivo.equals("JAVAFX_MEDIA")) {
                javafx.scene.media.MediaPlayer mediaPlayer = (javafx.scene.media.MediaPlayer) player;
                return (long) (mediaPlayer.getCurrentTime().toSeconds());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this, 
            "Error al ejecutar acción: " + e.getMessage(), 
            "Error de Reproducción", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        return 0;
    }

    @Override
    public void run() {
        try {
            while (true) {
                Thread.sleep(500);
                
                if (player != null && estaReproduciendo() && !estaPausado()) {
                    long posicionActual = getPosicionActual();
                    long duracionTotal = getDuracionTotal();
                    
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        Tiempo.setText(formatearTiempo(posicionActual) + " / " + formatearTiempo(duracionTotal));
                        
                        if (duracionTotal > 0) {
                            int progreso = (int) ((posicionActual * 100) / duracionTotal);
                            BarraProgreso.setValue(progreso);
                        }
                    });
                }
            }
        } catch (InterruptedException ex) {
    javax.swing.JOptionPane.showMessageDialog(ReproductorMP3.this,
    "Error al ejecutar acción: " + ex.getMessage(),
    "Error de Reproducción",
    javax.swing.JOptionPane.ERROR_MESSAGE);

        }
}
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Archivo;
    private javax.swing.JProgressBar BarraProgreso;
    private javax.swing.JButton Detener;
    private javax.swing.JLabel Estado;
    private javax.swing.JButton PlayPause;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}